###
GET http://localhost:9000/api HTTP/1.1

###
GET http://localhost:9000/api/2 HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "name": "Pedro",
    "age": 2,
    "class": "C"
}

###
DELETE http://localhost:9000/api/3 HTTP/1.1

###
PUT http://localhost:9000/api/2 HTTP/1.1
Content-Type: application/json

{
    "age": 21,
    "class": "B"
}